import { FormTask } from "@/app/to-do/components/form-task";
import { Metadata } from "next";


export const metadata: Metadata = {
  title: "App To-do - Crear tarea",
  description: "Generated by create next app",
};


export default function createPage() {
  return (
    <section>
      <h1 className="text-center text-3xl font-bold">
        Crea una <span className="text-blue-600">nueva tarea</span>{" "}
      </h1>
      <FormTask />
    </section>
  );
}
