
import ToDoPage from "@/app/to-do/components/view";
import { Task } from "@/app/api/to-do/route";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "App To-do - Lista de tareas",
  description: "Generated by create next app",
};

export default async function Page() {
  const response = await fetch('http://localhost:3000/api/to-do', {
    cache: 'no-cache',
    next: { revalidate: 10}
  });
  const data: Task[] = await response.json();

  // Pasar los datos al componente cliente (Index)
  return <ToDoPage data={data} />;
}
